sudo: false

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode8.3

language: c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lv2 fftw meson ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq lv2-dev libfftw3-dev python3-pip ninja-build; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -H pip3 install --upgrade pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip3 install meson; fi

script:
  - mkdir -p build
  - cd build
  - meson .. --buildtype release --strip
  - ninja -v
  - sudo ninja install
  
# deploy:
#   provider: releases
#   api_key:
#     secure: ${GH_TOKEN}
#   file_glob: true
#   file: bin/*
#   skip_cleanup: true
#   overwrite: true
#   on:
#     repo: lucianodato/noise-repellent
#     tags: true